@RD /S /Q "E:\Ayet\Jquery Cms\jquery-cms-2\jquerycms\"
@RD /S /Q "E:\Ayet\Jquery Cms\jquery-cms-2\masterpage\"
@RD /S /Q "E:\Ayet\Jquery Cms\jquery-cms-2\adm\"
@RD /S /Q "E:\Ayet\Jquery Cms\jquery-cms-2\admin\"
@RD /S /Q "E:\Ayet\Jquery Cms\jquery-cms-2\locale\"
@RD /S /Q "E:\Ayet\Jquery Cms\jquery-cms-2\lib\"
@RD /S /Q "E:\Ayet\Jquery Cms\jquery-cms-2\zSql\"

del "E:\Ayet\Jquery Cms\jquery-cms-2\.htaccess"
del "E:\Ayet\Jquery Cms\jquery-cms-2\img.php"
del "E:\Ayet\Jquery Cms\jquery-cms-2\img_.php"
del "E:\Ayet\Jquery Cms\jquery-cms-2\img_propmax.php"
del "E:\Ayet\Jquery Cms\jquery-cms-2\locmapaponto.php"
del "E:\Ayet\Jquery Cms\jquery-cms-2\seobusca.php"